### PR TITLE
Implement preference listener

### PR DESCRIPTION
**Pull request by mobrembski**
No need to use restart to see changes made in settings.
Sorry, i've based it on my other branch, but you can cherry-pick if you dont merge google-geocoding first

### CODE REVIEW

**Comment by jilleb** [comment]
This one is beautiful!!
It works nicely and intuitive. 👍 


I've found only a small bug, and that's when a clock has an imageindicator, it will not set the imageindicator when switching back from "High contrast" mode:
image


But I think it's an easy fix, I'll check it in the upcoming days.

**Comment by mobrembski** [comment]
To be honest, i can't find difference between those pictures :D
But i saw that needle is becoming white, which i think it should be red.

**Comment by jilleb** [comment]
haha, yeah the needle doesn't get updated to the right theme.
There are 2 cases:

- clock uses imageIndicator (picture as needle)
- clock uses a non-imageIndicator, like HalfLineIndicator. This has an indicatorLight effect, which is a gradient behind the needle.

I tried a quick and dirty fix, but it doesn't work.
What happens now is that this causes the wrong needle to be displayed when switching themes. If you go from Mustang GT to VW GTI, it will not have the right needle.
The other way around, from starting up in VW GTI, moving to Mustang GT, does work.

I haven't analysed the entire onPreferencesChangeHandler, but I guess it might be something there, where it forgets to set the right imageindicator.

**Comment by jilleb** [comment]
Then the VW GTI needle looks like this:

image

Instead of this:
image

**Comment by jilleb** [comment]
@mobrembski , I think I've found where it goes wrong.

MainCarActivity handles the themes and switching of themes when the preference changes.
DashboardFragment handles the rest of it all, including theme-specific needle-stuff. The theme-specific needle-stuff isn't updated when the theme is changed. It is updated when switching between high-vis-rays and needle.

The way the app determines whether or not it needs a "imageIndicator" or "HalfLineIndicator" is a bit crude. I'll see what I can do to improve it.

**Comment by jilleb** [comment]
For the time being, I'll make it in such a way that themes with sv_indicatorColor == @color/aqua, will have ImageIndicator. I'll make sure the styles.xml is a bit more structured and clean, so we can use the styles in the right way :-)

**Comment by mobrembski** [comment]
Interesting, if so, it means that just adding preference change listener on theme change will fix that. I will take a look at it in free time.
Do you added your changes in styles.xml?

**Comment by jilleb** [comment]
I'm not finished for the full 100%, but hopefully today I'll be able to do so :-)

**Pull request merged**
