### PR TITLE
Vex-base version 4.3

### PR DESCRIPTION
**Pull request by javigody**
Vex-base version updated to 4.3
Updated spanish translation 
Updated gradle version to 4.6
Updated some google services.
Teste on desktop head unit.

### CODE REVIEW

**Comment by jilleb** [comment]
Really nice work! :-) I'll merge the pull request tonight.

**Comment by javigody** [comment]
Needs revision, no data output.

**Comment by jilleb** [comment]
Hmm, I get a lot of onSchemeChanged() errors..

**Comment by javigody** [comment]
New array with providers needed. I will try to solve the problem. Sorry for the inconvenience.

**Comment by jilleb** [comment]
Ah no problem, don't worry. I'm a software tester, not a professional developer myself 🤣

**Pull request merged**
